arcgis:
  client_name: Macspoc - dev 
  wc_url: https://maconbibb.spatialitics.net
  portal_url: https://maconbibb.spatialitics.net/portal
  servers: [server]
  linux_backup_location:                # only for linux environment 
  backup_location: E:\GIS_Backups\Dev
  retention_days :                      # keep this blank for azure & aws

cloud_provider:                         # allowed values : azure, aws, blank

secret_provider:                        # allowed values : key vault key, Secret manager key, base64 encoded
  portal_username: cG9ydGFsYWRtaW4=
  portal_password: WUdGWDA3NTM=
  smtp_username: bWFjc25vdGlmaWNhdGlvbnNAQ3liZXJ0ZWNoLkNvbQ==
  smtp_password: QVg1QDg4SDY=

azure:
  client_id: 
  client_secret: 
  tenant_id: 
  key_vault: 
  connection_string : 
  container_name: 

aws: 
  region: 
  secret_name:   
  bucket_name: 
  s3_prefix: 

email:
  smtp_server: "smtp.office365.com"
  smtp_port: "587"
  email_recipients: ["prathamesh.dabekar@Cybertech.Com"]